### PR TITLE
Horizontal Layout Updates

### PR DESCRIPTION
**Pull request by kvnify**
Updates to ensure 24 hours shown in horizontal layout. Also further updates to ensure headers and time supplementary views are fixed to the top/side of the scroll view rather than bouncing when you reach the elastic regions. This also ensure the gird lines do not end abruptly at the bounds of the scroll view.

### CODE REVIEW

**Comment by ararog** [comment]
+1 for these improvements

**Comment by khendry** [comment]
Thanks. I have more on the way.

**Comment by ararog** [comment]
@khendry I believe you should start another project with a new name, give the credits to Eric and keep improving this awesome control.

**Comment by khendry** [comment]
I'd been thinking that as well. Thanks for the suggestion.  I probably will do that in the near future.

**Comment by Bautistax** [comment]
and add parse so you can remotely add events in the cloud

**Comment by BadChoice** [comment]
Checkout my fork https://github.com/BadChoice/RVCalendarWeekView
It is updated and with some new features 👯

**Pull request closed without merging**
